language: node_js
node_js:
- 10.2.1
before_install:
- openssl aes-256-cbc -K $encrypted_d0045aba1dea_key -iv $encrypted_d0045aba1dea_iv
  -in travis/helseci.key.enc -out travis/helseci.key -d
- git clone https://github.com/navikt/github-apps-support.git
- export PATH=`pwd`/github-apps-support/bin:$PATH
- export GH_TOKEN=$(generate-installation-token.sh `generate-jwt.sh ./travis/helseci.key
  $GITHUB_APP_ID`)
- export COMMIT_SHORT=$(git rev-parse --short HEAD)
- export ORIGINAL_COMMITTER=$(git log -1 --pretty=format:'%an <%ae>')
- echo -e "machine github.com\n  login $GH_TOKEN" > ~/.netrc
install:
- npm install
before_script:
- npm test
script:
- npm run build
- docker build . -t navikt/pleiepengesoknad:$COMMIT_SHORT
- |
  set -e
  if [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ]; then
    echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
    docker push $DOCKER_IMG_NAME:$COMMIT_SHORT
    git clone https://x-access-token:$GH_TOKEN@github.com/navikt/helse-iac.git
    cd helse-iac
    ./set-image.sh preprod/$APP_NAME/naiserator-sbs.yaml $DOCKER_IMG_NAME:$COMMIT_SHORT
    ./set-image.sh prod/$APP_NAME/naiserator-sbs.yaml $DOCKER_IMG_NAME:$COMMIT_SHORT
    git config user.name team-helse[bot]
    git config user.email team-helse[bot]@users.noreply.github.com
    git add preprod/$APP_NAME/naiserator-sbs.yaml
    git add prod/$APP_NAME/naiserator-sbs.yaml
    git commit -m "Bump $APP_NAME" -m "Caused by $TRAVIS_BUILD_WEB_URL" --author "$ORIGINAL_COMMITTER"
    git push https://x-access-token:$GH_TOKEN@github.com/navikt/helse-iac.git master
    cd ..
    fi
env:
  global:
  - APP_NAME=pleiepengesoknad
  - DOCKER_IMG_NAME=navikt/pleiepengesoknad
  - GITHUB_APP_ID=19726
  - secure: aaldNexuO9wGZFgBBs3uxi/DqtYgVfwrbzTUIUOcASkJE49vHYtE+79PhWH88rof5gnU07TKyune8a/rzgqefKz+SDsxQtWnUi1tr2MFIRsxEGqHBbNZ9XFAsb7zk0EjuvCADPJzkBYuvX/8qqEnwEVgObFUQPJnKYAf/XDeL6X/4DG7ya8PxwyAK6dKbNCp+6xpKsiFV4/+wXZXQTS7hK6I9d4pcierl7Hez/eKjFDuWfqj3+94Qt7XJpzFtGInsr3jRn4KMD0KuZws0NYJ+kIbfxpeacoUS6qeLb1UBb8vOlMmdUnQfH1VqcjWSgXNrmN25eB+mMGW3tL4PxKE8yZEPRfqqlZpUg6iybMbcIopYy3MUFfrPLhcfKWUf+hK5yrY88moyXoauNhy5UOQGIMy7Rv4omlF8R3d4cBv2zTBGHEkXtm8Amh+Ez2sg4UHCS2DtSDpBmk8M3CmNMOg+Og1n/Hz6Fbq1yIqSsFirw2rlPu35gB9sbZXE0Mzqc5RINAkMsK5zIrq4UKu/j6NWXlVHI9o3Rjkf9AiNWiC1RbKzfYLfyyAksd7ltVMJJLfTJX24tgRsKpxaD5NaGEnY9SsCEZgqxgJx0E972UfBfSy7WAAoz0F98x5wy67BhXTX2I24kM32w/1y/KxRztpgeYOHPUmrXPagpoBn6kpl7w=
  - secure: RoU3ZHungIldAcabyL+M3MbYtS7HpIEBuGOsp+wm5TIQ2dMzopnUwOciDlknKGvPfTE6XKTceWmEV2L3Rn6WQvb9oL2G4572fpvqhU3UrywzBCH/alQNB+B8RpUU+JCkWomTOC6OnNkOVt9NB3c5G5aTnbCI4VrGOsAFu4Qfi1jJnpgfEuy1RixKaxkouayY4xGVryNZ9vBl+wWtWxZXcBBmdZnJP6KQVVv19hvXFPgUCbcGmXYvqZ8BPZXr4VyGvUwBjFtiXEmqQ0SPQ1eE/Wa9H2mtvWNvbhtuj5ZdvEb1OzV0Ry3t8MvG4vGXoA9dGMFDHeN3fllW96iVKQ98x0dBK1rxvFZgN9xISK5fj7Ye59JHGXnmmyOJm4O/fJuCOEw52ZGJGgDLvVz3M3khY/TXlSE0EZHOPLE7AB9GP3aLMEnkAbl5Ywm992LmvrSDBbhBC0kdTT2FUS+GlspsTey6yKHcFC+HmliGzWfOCkwHwfMX/w9q6hKzorz2nidpBjaYy95hLkoLnRksIJhhD0Lt9AbRGkoZq5d0/R55+QjFHLZ+Y2rZkc+a6Zs6+PAFtoLWAIrkHd8c4QK6bythb8ue7c5kYDItMgDaCsbZzSpufBiriD/dbE5OquBa7ro2HXCiTMrkj/1j1jvbHdFX40Z6A/FfYQiwH7laulFlYh8=
branches:
  only:
    - master
