language: node_js
node_js:
- 10.2.1
before_install:
- openssl aes-256-cbc -K $encrypted_d0045aba1dea_key -iv $encrypted_d0045aba1dea_iv
  -in travis/helseci.key.enc -out travis/helseci.key -d
- git clone https://github.com/navikt/github-apps-support.git
- export PATH=`pwd`/github-apps-support/bin:$PATH
- export GH_TOKEN=$(generate-installation-token.sh `generate-jwt.sh ./travis/helseci.key
  $GITHUB_APP_ID`)
- export COMMIT_SHORT=$(git rev-parse --short HEAD)
- export ORIGINAL_COMMITTER=$(git log -1 --pretty=format:'%an <%ae>')
- echo -e "machine github.com\n  login $GH_TOKEN" > ~/.netrc
install:
- npm install
before_script:
- npm test
script:
- npm run build
- docker build . -t navikt/pleiepengesoknad:$COMMIT_SHORT
- |
  set -e
  if [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ]; then
    echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
    docker push $DOCKER_IMG_NAME:$COMMIT_SHORT
    git clone https://x-access-token:$GH_TOKEN@github.com/navikt/helse-iac.git
    cd helse-iac
    ./set-image.sh preprod/$APP_NAME/naiserator-sbs.yaml $DOCKER_IMG_NAME:$COMMIT_SHORT
    ./set-image.sh prod/$APP_NAME/naiserator-sbs.yaml $DOCKER_IMG_NAME:$COMMIT_SHORT
    git config user.name team-helse[bot]
    git config user.email team-helse[bot]@users.noreply.github.com
    git add preprod/$APP_NAME/naiserator-sbs.yaml
    git add prod/$APP_NAME/naiserator-sbs.yaml
    git commit -m "Bump $APP_NAME" -m "Caused by $TRAVIS_BUILD_WEB_URL" --author "$ORIGINAL_COMMITTER"
    git push https://x-access-token:$GH_TOKEN@github.com/navikt/helse-iac.git master
    cd ..
    fi
env:
  global:
  - APP_NAME=pleiepengesoknad
  - DOCKER_IMG_NAME=navikt/pleiepengesoknad
  - GITHUB_APP_ID=19726
  - secure: xmbQCdY5OjCkQH8RDVRoFQ7+wanOzFzYvsijgIhN5SXTDpQaDQYRlyM5imsOOGRoARryb4+2RkZK2J0Oxk5WOR++WuHRdarke4T6RGfV0IvaZim/69FZk5j6aHKppRNwOd2pD7Y+S7bVHq8lFCvkXwIzt77cJw1KdWX7jyGTALT7C3L3UoNf3755rGcTc2f0Oa273W0fRS9fvrmzlI70trhBZc96MpuLkoBXtqQrZenmulEfFa51Kom2mBlfiseWsnyBUGwpaojIeK0kfNdsYDXLfgPLdso47EQAVrz10Zwhs6OPBzaM4KH1VbjjrM5D/s7tV37U5f0GN7YeDszbCo3SDrY2jdBq9N0L+ACd8tpe0PWdffIfr0NrC9P2mK7wXzLDS9iaKccuvGODvCwnQaV2qIEF3hajp7T1gvDmHpHIPjjA8Wc+iGwAXZcdRuVzfS6+B8L3cuJMEgbTCf/HIBVhd0eWnRGyNwzdkb6WU6AnaKNsjTMhZPnE/7iaAmrEJv2jW4Fyi3jg+1qhCLzYdNkuwe0WYT0BcNIX9zd9mYgFGzOl9q1o2j7THDUXNHIOGbLQ50HWn7FijyH8PiLV87LybAzxLN3x3nLiLJt0fLaV1bA5a8jwf6ol+RiN/Bn4RuLFTfEIDPv8F8t70Aa+lcoWU5FB9a5thBCRBTug5Xc=
  - secure: GgIUkjTCmp1fObqdvF11Wq09kDd6wmQzThcZsEfvMUW55t58S5+osNE9xc3RuxsSrjgsZMKnNcqcMv/1+BqLFVUcnUzHwWyQpF7nfPdGLaU3l5qqUFN2drG+bbPrvLtCz44vPxm190T4kNFb4orYhteD91VIfLGN9YHzrDtEgIf9Rn9JVbhI9OIhoBCNNU7YVN9FPKZKH7bDw13IOULvU30qFXnXSzHGcuU82k/UWqkPafuCSA8c+nZSCYQmjNlvewTrnqvd1kpMmag3ErCn0kvLTtBUaNwdpqUwCWL1lPX92JiAR6l27KWWZ4Ti4x9IDQWRMJR9W6DXYjEP1RjkTs96oHY8Q2/bpI9bNAQJ9/O6SdxJT3ucIZNwkcpeHiQuHr24ymBg6uU0uIl5FvkiTTTcpXCfgmI4Qg+Xahs/tN6MIzzTZuBu81n0oCDMNHVuqElSKUKndRVMRF0AzYm0SKOk+uavNyzpAbQur9d0fbDbVFBdRucKWTEqXvoNV2j+YPs1bdGGE3OXwzcxzrRfTHzlY/rJhQ2yJG6SHeN100bUR/aP/FiHHGaaQyNecWd2eJM8yucwehyn+1jppOL5rgqVyT/qUh6U73HX+mqv6O3YLJVe9q/gf5KEpkWRiyvm8dJjuEahJxAoi/DKSgzhzMecivXzYDnfiofKmK4/Gmg=
branches:
  only:
  - master
