language: node_js
node_js:
- 10.2.1
before_install:
- openssl aes-256-cbc -K $encrypted_d0045aba1dea_key -iv $encrypted_d0045aba1dea_iv
  -in travis/helseci.key.enc -out travis/helseci.key -d
- git clone https://github.com/navikt/github-apps-support.git
- export PATH=`pwd`/github-apps-support/bin:$PATH
- export GH_TOKEN=$(generate-installation-token.sh `generate-jwt.sh ./travis/helseci.key
  $GITHUB_APP_ID`)
- export COMMIT_SHORT=$(git rev-parse --short HEAD)
- export ORIGINAL_COMMITTER=$(git log -1 --pretty=format:'%an <%ae>')
- echo -e "machine github.com\n  login $GH_TOKEN" > ~/.netrc
install:
- npm install
before_script:
- npm test
script:
- npm run build
- docker build . -t navikt/pleiepengesoknad:$COMMIT_SHORT
- |
  set -e
  if [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ]; then
    echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
    docker push $DOCKER_IMG_NAME:$COMMIT_SHORT
    git clone https://x-access-token:$GH_TOKEN@github.com/navikt/helse-iac.git
    cd helse-iac
    ./set-image.sh preprod/$APP_NAME/naiserator.yaml $DOCKER_IMG_NAME:$COMMIT_SHORT
    ./set-image.sh prod/$APP_NAME/naiserator.yaml $DOCKER_IMG_NAME:$COMMIT_SHORT
    git config user.name team-helse[bot]
    git config user.email team-helse[bot]@users.noreply.github.com
    git add preprod/$APP_NAME/naiserator.yaml
    git add prod/$APP_NAME/naiserator.yaml
    git commit -m "Bump $APP_NAME" -m "Caused by $TRAVIS_BUILD_WEB_URL" --author "$ORIGINAL_COMMITTER"
    git push https://x-access-token:$GH_TOKEN@github.com/navikt/helse-iac.git master
    cd ..
    fi
env:
  global:
  - APP_NAME=pleiepengesoknad
  - DOCKER_IMG_NAME=navikt/pleiepengesoknad
  - GITHUB_APP_ID=19726
  - secure: 0lWqvNQYtxWVxjReBQia1NaYUZzqD34XXmY3/JLDearKL33PDog4Ffgjv1nrAuc83Cb2ts7R+Lf2VKEYWTvPBQe/fkVZ9eoOQ6cj59aVAj9rxyoOBVNLR0tnEZ/bWSCipSexnmpvABckySPEDfHIl2FH8m9beZzMpwRbpJ8fLa/egjfEmm1siikih/aI+r/JD1MTZqKsxSxxNx5OfZ77WpKTx/13N++zx0OM0iXbshGd2RIUFhLxEnQJttI5IadY5/AzehlfvOOR/nAI/5dUM125JUKUxrt48U/8FWXueuunpkhpl4hBKDHcrYnVt5PZ9gEbqxAqLxYSt6lVtajn9zxdCFFlAFyCxJymwxl7AiNEZTltVXLolSgpx5xraR1VJAo+J3Q4SWwcKsvb3nOLRn6xI3DFJikSGG3OJ7qINtlGLYi0qQf9Xne1o4o64pi2ineAY0dKW0uftKjN+Q6qK9aF3EIcKb+hVqM3K0npuf1k/D0ttDZEjiqUVVLtn+5r43rOOaP/6aTBESkwnss/HEonP9SoQ2cyLWm4/6xGax1Ebq1SIJwrpAeSSdSOHsKWoC2JmIC/cd+ObwkOA5yxoIIZzBteOtCkHDWJNhKBfXDBNVypJOjBej9hoorhqHAcYnPLYpN0flFAIKF4sBkildwugr+4FvOi2hO+Z48QUH0=
  - secure: pe/lHZANxFI5q3mDR9Ky9/KvRAvVuIASmMJHd42FO+nhIXHzaiaurQFSD/CtzQ6r1znj8IPxIgS/oe0ZBuXqYExNnQ0YTNDg8tfdaMLvPZHnz2OOe9POB0M9EKHtaOz/Cieiq98IhrI8HIDdsjZfghTCSjsS5etor1AP8Fgniall0F1xiaahPCC0sRsd3klkEr3GkDa4bYH8tUi3cNRHDAhsW8YvajZYziFkUG4uaMAV/jtMsfQFw2repRLeAsty7zvZPJZl5pFrpcxjxK4WxnPWeduLyUwetmd3l3Js3W74Y+yqQrEF6W2d5W3qwP7vwlIQ2BU11q+IH2YJShwWMFUBnT+iqRFAWyx40J7uU1gGkcuyj5scf308ZULZ/3a9KdEwxSa8IMHVRbRTH0mUnLJfc8s8eJaFMW+f+MOkQwDgRmzats25SPXXWZ5h6YW8rG5IynCBP9+Avt5j9ceIyJrWNqghhr54b+3yb7aYBPoWZeDKwNI+2v4UkCPnkMfBXbujN703kzG89rkuA+IldaqbVC5g03XraziIAFHF8oZ0yWE2aRgjzcN/Wy1nNWy9xuxnnQ2Cb+VsgmUC3l4r/zV/fMerSa/fhiFCzTwEqi0nxXXvzbP2yOcDo+T9cHmphyRs3f7IzpJ9YCyWJlHZyUM32P6Vk7SfKblYXJvI3KY=
