version: 2.1
orbs:
  nais: 'navikt/nais-deployment@1.1.0'

jobs:
  build:
    working_directory: ~/pleiepengesoknad
    docker:
      - image: 'circleci/node:10.2.1'
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-{{ checksum "package.json" }}
      - run: npm install
      - run: npm test
      - run: npm run build
      - save_cache:
          paths:
            - ./node_modules
          key: node-{{ checksum "package.json" }}
      - nais/docker-deploy:
          image: navikt/pleiepengesoknad
  check:
    working_directory: ~/pleiepengesoknad
    docker:
      - image: 'circleci/node:10.2.1'
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-{{ checksum "package.json" }}
      - run: npm install
      - run: npm test
      - run: npm run build
      - save_cache:
          paths:
            - ./node_modules
          key: node-{{ checksum "package.json" }}

workflows:
  version: 2
  deploy-docker-and-nais:
    jobs:
      - check:
          filters:
            branches:
              ignore:
                - master
                - /dev-.*/
      - build:
          context: NAIS deployment
          filters:
            branches:
              only:
                - master
                - /dev-.*/